name: moglog
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate deployment package 
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: moglog
          environment_name: Moglog-env
          existing_bucket_name: elasticbeanstalk-us-east-1-014783202930
          region: us-est-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip